module.exports = {
  content: [
    {
      raw: '',
      extension: 'html',
    },
    './templates/**/*.html',
    './**/*.html',
    './static/js/**/*.js',
  ],
  theme: {
    extend: {},
  },
  safelist: [
    'bg-blue-600',
    'hover:bg-blue-700',
    'text-white',
    'text-blue-700',
    'text-gray-600',
    'rounded',
    'rounded-xl',
    'shadow',
    'shadow-xl',
    'w-full',
    'p-2',
    'p-10',
    'text-2xl',
    'text-4xl',
    'font-bold',
    'font-extrabold',
    'block',
    'flex',
    'min-h-screen',
    'justify-center',
    'items-center',
    'transition',
    'inline-block',
    'max-w-xl',
    'max-w-lg',
    'space-y-4',
    'mt-10',
    'mx-auto',
  ],
  plugins: [],
}